config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get '/swapboard', to: 'home#swapboard', as: 'user_root'
  get ':group_name/swapboard', to: 'home#swapboard', as: 'group_swapboard'

  get '/invite/:invite_token', :to => "members#invite", :as => "invite_confirmation"
  get 'profile/:id/complete_profile', to: 'users#temporary', as: :complete_profile
  get 'groups/:group_name/email_opt/:id', to: 'members#email_opt', as: :email_opt
  patch 'profile/:id/update_profile', to: 'users#temporary_update', as: :complete_profile_update

  resources :users, only: [:edit, :update], path: 'profile', as: :profile do
    resources :meals, only: [:index, :show]
  end
  resources :groups, only: [:index, :new, :create, :show, :update, :destroy], param: :name do
    resources :members, only: [:new, :index, :create, :destroy, :show, :update]
    resources :messages, only: [:create, :destroy]
    resources :weeks, only: [:new, :create, :show, :update] do
      resources :meals, only: [:index, :create, :new, :show, :update]
    end
  end

  resources :meals, only: [] do
    resources :reviews, only: [:create, :update]
  end

  devise_for :users, controllers: { sessions: 'sessions' }

  namespace :admin do
    resources :users
    resources :groups
    resources :meals
    resources :reviews
    resources :meal_categories
    resources :containers
    resources :members
    resources :weeks
    resources :testing_comments

    root to: "users#index"
  end

  resources :testing_comments, only: [:new, :create]

  root "home#index"
end

app/models/week.rb
class Week < ActiveRecord::Base
  belongs_to :group
  has_many :meals

  def is_past?
    Date.today > (start_date)
  end
end

app/controllers/admin/weeks_controller.rb
module Admin
  class WeeksController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Week.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Week.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_view_active

  def show
    authorize_user_group(params[:group_name])
    @week = Week.find(params[:id])
    @is_admin = set_admin(@group)
    @user_meal = current_user.week_meal(@week)
    @list_users = @group.users.reject { |user| user.id == current_user.id }
  end

  def update
    authorize_admin(params[:group_name])
    @week = Week.find(params[:id])

    if @week.update(week_params)
      redirect_to group_path(@group.name), alert: 'Successfully updated.'
    else
      render :edit
    end
  end

  def new
    authorize_admin(params[:group_name])
    @week = Week.new
    @days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
  end

  def create
    authorize_admin(params[:group_name])

    number = params[:number_of_weeks].to_i

    if params[:add]
      if params[:number_of_weeks].empty?
        return redirect_to group_path(@group.name), alert: "Did you put a number in the box?"
      end
      start = @group.weeks.last.start_date + 7
      default_values = {
        swap: Date.parse(week_params[:swap_date]).wday,
        location: @group.weeks.last.swap_location,
        time: @group.weeks.last.swap_time
      }
    else
      if invalid_input?
        return redirect_to new_group_week_path(@group.name), alert: "Please enter all of this info. You can change details later!"
      end
      start = Date.parse(week_params[:start_date])
      default_values = {
        location: week_params[:swap_location],
        time: week_params[:swap_time],
        swap: day_map[week_params[:swap_date].downcase.to_sym]
      }
    end

    weeks = ScheduleMaker.new(start, default_values, number).create_weeks
    Week.transaction do
      weeks.each do |week|
        week.group_id = @group.id
        week.save!
      end
    end

    redirect_to group_path(@group.name)
  end

  private

  def week_params
    params.require(:week).permit(:start_date, :swap_date, :swap_location, :paused, :swap_time)
  end

  def start_date_param
    date = week_params[:start_date].split("-")
    "#{date[2]}-#{date[0]}-#{date[1]}"
  end

  def sort_weeks
    @group.weeks.sort_by { |week| week.start_date }
  end

  def find_week_index
    @weeks.find_index(@group.current_week)
  end

  def authorize_user_group(group_name)
    if current_user.groups.pluck(:name).any? { |name| name == group_name }
      @group = Group.where(name: group_name).first
    else
      redirect_to user_root_path
    end
  end

  def authorize_admin(group_name)
    @group = Group.where(name: group_name).first
    unless @group.admin == current_user.id
      redirect_to group_path(@group.name)
    end
  end

  def invalid_input?
    week_params[:start_date].empty? ||
    week_params[:swap_date].nil? || 
    week_params[:swap_location].empty? || 
    week_params[:swap_time].empty? || 
    params[:number_of_weeks].empty?
  end

  def set_view_active
    @active_week_view_path = "weeks_active"
  end

  def day_map
    {
      sunday: 0,
      monday: 1,
      tuesday: 2,
      wednesday: 3,
      thursday: 4,
      friday: 5,
      saturday: 6
    }
  end
end

app/views/weeks/_calendar.html.erb
<div class="row">
  <div class="eight columns">
    <h5>Swapping Schedule</h5>
  </div>
  <% if @is_admin %>
    <div class="three columns">
      <p class="add-weeks-link"><%= fa_icon "plus" %> Add weeks</p>
      <div class="add-weeks-form" style="display:none;">
        <%= form_for(@week, url: group_weeks_path(@group.name)) do |f| %>

          <%= render partial: "shared/alerts" %> 

          <%= hidden_field_tag :add, "true" %>
          <%= f.hidden_field :swap_date, value: @group.weeks.last.swap_date %>

          <%= label_tag :number_of_weeks, "Number of weeks" , class: "field-label" %>
          <%= number_field_tag :number_of_weeks %>

          <%= submit_tag "Add" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="u-full-width">
    <div class="scroller" <%= "data-current-week-index=#{@this_week_index}" %>>
      <% @weeks.each_with_index do |week, index| %>
        <div class="week-card">
          <%= render partial: "weeks/week_card", locals: { week: week, group: @group } %> 
        </div>
      <% end %>
    </div>

    <div class="slider-arrows">
      <div class="weeks-arrow-right"><span class="fa fa-angle-right"></span></div>
      <div class="weeks-arrow-left"><span class="fa fa-angle-left"></span></div>
    </div>

  </div>
</div>

app/views/weeks/_week_card.html.erb
<h5>Week of <%= (week.start_date).strftime("%m/%d") %></h5>

<% if week.paused %>
  <h6><%= fa_icon "exclamation-circle" %>  Swap paused</h6>
<% end %>

<% if @is_admin %>

  <%= form_for(week, url: group_week_path(@group.name, week), method: :put) do |f| %>

    <%= render partial: "shared/alerts" %> 

    <%= f.label :swap_date, class: "field-label" %>
    <%= f.date_field :swap_date %>

    <%= f.label :swap_location, class: "field-label" %>
    <%= f.text_field :swap_location %>

    <%= f.label :swap_time, class: "field-label" %>
    <%= f.text_field :swap_time %>

    <%= f.label :paused do %>
      <%= f.check_box :paused %>
      <span class="field-label">Pause this week's swap</span>
    <% end %>
    <br>

    <%= f.submit "Update week" %>
  <% end %>

<% else %>
  <p class="meal-details">Swappin time: <%= @week.swap_time %> on <%= (week.swap_date).strftime("%A %m/%d") %></p>
  <p class="meal-details">Swap destination: <%= week.swap_location %></p>

<% end %>

<h5>The meals</h5>

<%= render partial: "home/swapboard_week_list", locals: { week: week } %>

app/views/weeks/new.html.erb
<div class="container">
  <%= render partial: "shared/toolbar", locals: { group: @group } %>
  <div class="row">
    <div class="ten columns">
      <h3>Create a schedule</h3>
    </div>
    <div class="two columns">
    </div>
  </div>

  <div class="row">
    <div class="u-full-width">

      <p>Don’t worry, swapper. You can update these details later if necessary.</p>

      <%= form_for(@week, url: group_weeks_path(@group.name)) do |f| %>

      <%= render partial: "shared/alerts" %> 

        <div class="field">
          <%= f.label :start_date, "1st week of swapping", class: "field-label" %>
          <%= f.date_field :start_date %>
        </div>

        <div class="field">
          <%= label_tag :number_of_weeks, "Number of weeks", class: "field-label" %>
          <%= number_field_tag :number_of_weeks %>
        </div>

        <div class="field">
          <%= f.label :swap_location, class: "field-label" %>
          <%= f.text_field :swap_location %>
        </div>

        <div class="field">
          <%= f.label :swap_time, class: "field-label" %>
          <%= f.text_field :swap_time %>
        </div>
        
        
        <div class="checkbox-area">
          <p>Swap day</p>
            <% @days.each do |day| %>
            <div class="radio-area">
                <%= label_tag :swap_date, day, class: "radio-label" %>
                <%= f.radio_button(:swap_date, day, class: "radio-button") %>
            </div>
            <% end %>
        </div>

        <div class="actions">
          <%= submit_tag "Create schedule" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/weeks/show.html.erb
<div class="container">
  <%= render partial: "shared/toolbar", locals: { group: @group } %>
  <div class="row">
    <div class="ten columns">
      <h3><%= "#{@group.name}'s Week of #{ @week.start_date.strftime("%m/%d/%Y") }" %></h3>
    </div>
  <div class="row">
    <div class="six columns boardered">

    <% if @is_admin %>

      <%= form_for(@week, url: group_week_path(@group.name, @week), method: :put) do |f| %>

        <%= render partial: "shared/alerts" %> 

        <%= f.label :swap_date, class: "field-label" %>
        <%= f.date_field :swap_date %>

        <%= f.label :swap_location, class: "field-label" %>
        <%= f.text_field :swap_location %>

        <%= f.label :swap_time, class: "field-label" %>
        <%= f.text_field :swap_time %>

        <%= f.label :paused do %>
          <%= f.check_box :paused %>
          <span class="field-label">Pause this week's swap</span>
        <% end %>
        <br>

        <%= f.submit "Update week" %>
      <% end %>

    <% else %>
      <p>Swap Date: <%= @week.swap_date %></p>
      <p>Swap Location: <%= @week.swap_location %></p>
    <% end %>

    </div>

    <div class="six columns boardered">
      <h5>My meal</h5>
      <% if @user_meal %>
        <p><%= @user_meal.name %> (<%= @user_meal.category.name %>) </p>
        <% unless @user_meal.recipe_url == "" || @user_meal.recipe_url.nil? %>
          <p><%= link_to "Recipe", @user_meal.recipe_url, :target => "_blank" %></p>
        <% end %>
       <p><%= link_to "More meal details", group_week_meal_path(@group.name, @week, @user_meal) %></p>
      <% else %>
        <%= link_to "Add my meal", new_group_week_meal_path(@group.name, @week) %>
      <% end %>
    </div>


    <div class="six columns all-meals">
      <div class="">
        <h5>All meals this week</h5>
        <%= render partial: "home/swapboard_week_list", locals: { week: @week } %>
      </div>
    </div>
  </div>
</div>