config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get '/swapboard', to: 'home#swapboard', as: 'user_root'
  get ':group_name/swapboard', to: 'home#swapboard', as: 'group_swapboard'

  get '/invite/:invite_token', :to => "members#invite", :as => "invite_confirmation"
  get 'profile/:id/complete_profile', to: 'users#temporary', as: :complete_profile
  get 'groups/:group_name/email_opt/:id', to: 'members#email_opt', as: :email_opt
  patch 'profile/:id/update_profile', to: 'users#temporary_update', as: :complete_profile_update

  resources :users, only: [:edit, :update], path: 'profile', as: :profile do
    resources :meals, only: [:index, :show]
  end
  resources :groups, only: [:index, :new, :create, :show, :update, :destroy], param: :name do
    resources :members, only: [:new, :index, :create, :destroy, :show, :update]
    resources :messages, only: [:create, :destroy]
    resources :weeks, only: [:new, :create, :show, :update] do
      resources :meals, only: [:index, :create, :new, :show, :update]
    end
  end

  resources :meals, only: [] do
    resources :reviews, only: [:create, :update]
  end

  devise_for :users, controllers: { sessions: 'sessions' }

  namespace :admin do
    resources :users
    resources :groups
    resources :meals
    resources :reviews
    resources :meal_categories
    resources :containers
    resources :members
    resources :weeks
    resources :testing_comments

    root to: "users#index"
  end

  resources :testing_comments, only: [:new, :create]

  root "home#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "pizza.svg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates_presence_of :email

  has_many :members
  has_many :meals
  has_many :reviews
  has_many :messages
  has_many :groups, through: :members

  has_and_belongs_to_many :diet_restrictions

  before_create :normalize_email

  before_destroy :delete_associated_members

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  def self.temporary(data)
    new_user = {
      email: data[:email],
      name: data[:name],
      password: rand(36**10).to_s(36),
      temporary: true
    }
    user = new(new_user)
    user.skip_confirmation!
    user.save!
    user
  end

  def invite_status(group)
    Member.where(group_id: group.id, user_id: id).take.status
  end

  def week_meal(week)
    meals.where(week_id: week.id).take
  end

  def group_meals(group)
    week_ids = group.weeks.pluck(:id)
    meals.select do |meal|
      week_ids.any? { |week_id| meal.week_id == week_id }
    end
  end

  def average_rating(group)
    week_ids = group.weeks.pluck(:id)
    group_meals = self.meals.select { |meal| week_ids.include?(meal.week_id) }

    all_ratings = []
    group_meals.each do |meal|
      all_ratings << meal.reviews.pluck(:rating)
    end
    all_ratings = all_ratings.flatten.compact

    unless all_ratings.empty?
      total = all_ratings.inject(&:+)
      count = all_ratings.count
      avg = total.to_f / count.to_f

      avg.round(2)
    else
      0
    end
  end

  private

  def normalize_email
    self.email = self.email.downcase
  end

  def delete_associated_members
    members.destroy_all
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:temporary, :temporary_update]
  before_action :set_view_active
  layout "simple", only: [:temporary]

  def edit
    @user = current_user
    # @diet_restrictions = DietRestriction.all
  end

  def update
    @user = current_user
    # @user.diet_restriction_ids = diet_params

    if @user.update(user_params)
      redirect_to edit_profile_path(@user), alert: 'Successfully updated.'
    else
      render :edit
    end
  end

  def temporary
    @user = User.find(params[:id])
    # @diet_restrictions = DietRestriction.all
  end

  def temporary_update
    @user = User.find(user_params[:id])
    update_params = user_params
    update_params["temporary"] = false

    if confirm_password
      @user.update(update_params)
      bypass_sign_in(@user)
      redirect_to user_root_path(@user), notice: "Success!"
    else
      flash[:alert] = "Password and matching confirmation are required"
      redirect_to complete_profile_path(@user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :city, :zip_code, :cooking_level,
      :diet_restrictions, :temporary, :id, :password, :password_confirmation, 
      :description, :avatar)
  end

  def diet_params
    params[:user][:diet_restriction_ids].reject { |diet| diet.empty? }
  end

  def confirm_password
    user_params[:password]!= "" && user_params[:password] == user_params[:password_confirmation]
  end

  def set_view_active
    @active_profile_view_path = "profile_active"
  end
end

app/views/users/edit.html.erb
<div class="container">
  <% unless current_user.groups.empty? %>
    <%= render partial: "shared/toolbar", locals: { group: current_user.groups.first } %>
  <% end %>

  <div class="row">
    <div class="six columns">
      <%= image_tag @user.avatar.url(:thumb), width: '50', class: 'img-circle profile-img' %>
      <h3 class="profile-header">My Profile</h3>
    </div>
    <div class="six columns">
      <%= link_to destroy_user_session_path, :method => :delete do %>
        <%= fa_icon "sign-out" %> Sign out
      <% end %>
    </div>
  </div>
  
  <div class="row">
    <div class="six columns boardered">
      <p><%= @user.email %></p>

      <%= form_for(@user, url: profile_path(@user.id), multipart: true) do |f| %>

       <%= render partial: "shared/alerts" %> 

        <%= f.label :name, class: "field-label" %>
        <%= f.text_field :name %>

        <%= f.label :description, 'Tell us about yourself', class: "field-label" %>
        <%= f.text_area :description %>

        <%= f.label :avatar, "Change Photo", class: "field-label" %>
        <%= f.file_field :avatar, accept: "image/*" %>

        <br><br>
        <%= f.submit "Update profile" %>
      <% end %>
    </div>
    <div class="six columns boardered">

      <div class="group-list">
        <h5>Groups</h5>
        <% @user.groups.each do |group| %>
          <p><%= link_to group.name, group_path(group.name) %></p>
        <% end %>

        <%= link_to new_group_path  do %>
          <p><%= fa_icon "plus" %> Nobody swaps alone. Start a new group here.</p>
        <% end %>
      </div>
    </div>

    <div class="six columns boardered">
      <div>
        <h5>My Meals</h5>
        <% @user.meals.each do |meal| %>
          <p><%= meal.name %> | <%= link_to "Meal details", group_week_meal_path(meal.week.group.name, meal.week.id, meal.id) %></p>
        <% end %>
      </div>
    </div>

    </div>
  </div>
</div>

app/views/users/temporary.html.erb
<div class="container">
  <div class="row">
    <div class="u-full-width boardered">

      <h5>Please finish filling out your profile to continue</h5>
      <p><%= @user.email %></p>

      <%= form_for(@user, url: complete_profile_update_path(@user)) do |f| %>

       <%= render partial: "shared/alerts" %> 

        <%= f.hidden_field :temporary %>
        <%= f.hidden_field :id %>

        <%= f.label :name, class: "field-label" %>
        <%= f.text_field :name %>

        <%= f.label :password, class: "field-label" %>
        <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %>
        <%= f.password_field :password, autocomplete: "off" %>

        <%= f.label :password_confirmation, class: "field-label" %>
        <%= f.password_field :password_confirmation, autocomplete: "off" %>

        <%= f.submit "Complete profile" %>
      <% end %>

    </div>
  </div>
</div>