config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get '/swapboard', to: 'home#swapboard', as: 'user_root'
  get ':group_name/swapboard', to: 'home#swapboard', as: 'group_swapboard'

  get '/invite/:invite_token', :to => "members#invite", :as => "invite_confirmation"
  get 'profile/:id/complete_profile', to: 'users#temporary', as: :complete_profile
  get 'groups/:group_name/email_opt/:id', to: 'members#email_opt', as: :email_opt
  patch 'profile/:id/update_profile', to: 'users#temporary_update', as: :complete_profile_update

  resources :users, only: [:edit, :update], path: 'profile', as: :profile do
    resources :meals, only: [:index, :show]
  end
  resources :groups, only: [:index, :new, :create, :show, :update, :destroy], param: :name do
    resources :members, only: [:new, :index, :create, :destroy, :show, :update]
    resources :messages, only: [:create, :destroy]
    resources :weeks, only: [:new, :create, :show, :update] do
      resources :meals, only: [:index, :create, :new, :show, :update]
    end
  end

  resources :meals, only: [] do
    resources :reviews, only: [:create, :update]
  end

  devise_for :users, controllers: { sessions: 'sessions' }

  namespace :admin do
    resources :users
    resources :groups
    resources :meals
    resources :reviews
    resources :meal_categories
    resources :containers
    resources :members
    resources :weeks
    resources :testing_comments

    root to: "users#index"
  end

  resources :testing_comments, only: [:new, :create]

  root "home#index"
end

app/views/shared/_alerts.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info"><%= flash[:alert] %></div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="row">
    <div class="seven columns footer-links">
      <% if current_user %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path %>
      <% end %>
      <%= link_to "Tell us what you think", new_testing_comment_path %>
      <% if current_user && current_user.super_admin%>
        <%= link_to "Admin tool", admin_root_path %>
      <% end %>
    </div>
    
    <div class="two columns">
      <p class="footer-content">Copyright © Crockswap</p>
    </div>
  </div>
</div>

app/views/shared/_group_nav.html.erb
<li class="username"><%= "#{group.name}" %></li>
<li><%= link_to "Swapboard", group_swapboard_path(group.name) %></li>
<% if group.current_week %>
  <li><%= link_to "Current swap", group_week_path(group.name, group.current_week.id) %></li>
<% end %>
<li><%= link_to "Group settings", group_path(group.name) %></li>

app/views/shared/_sticky_nav.html.erb
<nav class="fixed-nav-bar">
  <div class="row">
    <div class="u-full-width">
      <div id="menu" class="menu">
        <% unless current_user %>
          <%= link_to root_path, { class: "clean-link" } do %>
            <span class="sitename">Crockswap</span>
          <% end %>
        <% else %>
          <% if current_user.groups.count > 1 %>
            <%= link_to groups_path, { class: "clean-link" } do %>
              <span class="sitename">Crockswap</span>
            <% end %>
          <% else %>
            <%= link_to user_root_path, { class: "clean-link" } do %>
              <span class="sitename">Crockswap</span>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_toolbar.html.erb
<div class="row toolbar">
  <div class="u-full-width">
    
    <div id="<%="#{params[:action]}_active"%>" class="toolbar-item">
      <%= link_to group_swapboard_path(group.name), class: "toolbar-link" do %>
        <%= fa_icon "tachometer" %> 
        <p  class="toolbar-link-text" >Swapboard</p>
      <% end %>
    </div>

    <div id="<%="#{@active_group_view_path}" %>" class="toolbar-item">
      <%= link_to group_path(group.name), class: "toolbar-link" do %>
        <%= fa_icon "users" %> 
        <p  class="toolbar-link-text" >Group</p>
      <% end %>
    </div>

    <div id="<%="#{@active_profile_view_path}" %>" class="toolbar-item">
      <%= link_to edit_profile_path(current_user), class: "toolbar-link" do %>
        <%= fa_icon "user" %> 
        <p  class="toolbar-link-text" >Profile</p>
      <% end %>
    </div>

  </div>
</div>