config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get '/swapboard', to: 'home#swapboard', as: 'user_root'
  get ':group_name/swapboard', to: 'home#swapboard', as: 'group_swapboard'

  get '/invite/:invite_token', :to => "members#invite", :as => "invite_confirmation"
  get 'profile/:id/complete_profile', to: 'users#temporary', as: :complete_profile
  get 'groups/:group_name/email_opt/:id', to: 'members#email_opt', as: :email_opt
  patch 'profile/:id/update_profile', to: 'users#temporary_update', as: :complete_profile_update

  resources :users, only: [:edit, :update], path: 'profile', as: :profile do
    resources :meals, only: [:index, :show]
  end
  resources :groups, only: [:index, :new, :create, :show, :update, :destroy], param: :name do
    resources :members, only: [:new, :index, :create, :destroy, :show, :update]
    resources :messages, only: [:create, :destroy]
    resources :weeks, only: [:new, :create, :show, :update] do
      resources :meals, only: [:index, :create, :new, :show, :update]
    end
  end

  resources :meals, only: [] do
    resources :reviews, only: [:create, :update]
  end

  devise_for :users, controllers: { sessions: 'sessions' }

  namespace :admin do
    resources :users
    resources :groups
    resources :meals
    resources :reviews
    resources :meal_categories
    resources :containers
    resources :members
    resources :weeks
    resources :testing_comments

    root to: "users#index"
  end

  resources :testing_comments, only: [:new, :create]

  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    # #temp prod view
    # render 'temp_index', layout: "simple"
  end

  def swapboard
    @user = current_user
    @groups = @user.groups
    @new_message = Message.new

    if @groups.empty?
      redirect_to new_group_path
    end
    if params[:group_name]
      @group = @groups.select { |group| group.name == params[:group_name] }[0]
      @is_admin = set_admin(@group)
    else
      if @groups.count > 1
        redirect_to groups_path
      end
      @group = @groups.first
      @is_admin = set_admin(@group)
    end
  end
end

app/views/home/_empty_week.html.erb
<div class="swapboard-week-links">
  No scheduled swappin' this week.
</div>

<div class="dashboard-table this-week empty-week">
  <div class="dashboard-table-row empty-week">
    <div class="dashboard-table-cell header empty-week">Swapper</div>
    <div class="dashboard-table-cell header empty-week">Dish</div>
    <div class="dashboard-table-cell header empty-week">Category</div>
  </div>

  <div class="dashboard-table-row empty-week">
    <div class="dashboard-table-cell empty-week"></div>
    <div class="dashboard-table-cell empty-week"></div>
    <div class="dashboard-table-cell empty-week"></div>
  </div>

</div>

app/views/home/_last_week.html.erb
<h6>Last Week's Swap</h6>
<div class="dashboard-table">
    <div class="dashboard-table-row">
      <div class="dashboard-table-cell header">Swapper</div>
      <div class="dashboard-table-cell header">Dish</div>
      <div class="dashboard-table-cell header">Stars</div>
    </div>
  <% @group.users.each do |member| %>
    <div class="dashboard-table-row">
      <div class="dashboard-table-cell"><%= member.name %></div>
      <div class="dashboard-table-cell">Hot dogs</div>
      <div class="dashboard-table-cell">
        <%= fa_icon "star-o" %>
        <%= fa_icon "star-o" %>
        <%= fa_icon "star-o" %>
      </div>
    </div>
  <% end %>
</div>

app/views/home/_leaderboard.html.erb
<h6>Leaderboard</h6>
<div class="dashboard-table leaderboard">
    <div class="dashboard-table-row">
      <div class="dashboard-table-cell header">Rank</div>
      <div class="dashboard-table-cell header">Swapper</div>
      <div class="dashboard-table-cell header">Average Rating</div>
    </div>
  <% @group.leaderboard_users.each_with_index do |member, index| %>
    <div class="dashboard-table-row">
      <div class="dashboard-table-cell">
        <%= index + 1 %>
      </div>
      <div class="dashboard-table-cell">
        <%= image_tag member.avatar.url(:thumb), width: '20', class: 'img-circle' %>
        <span class="week-meal-name">
          <%= member.name %>
        </span> 
      </div>
      <div class="dashboard-table-cell"><%= member.average_rating(@group) %></div>
    </div>
  <% end %>
</div>

app/views/home/_search_recipes.html.erb
<h6>Search Recipes</h6>
<input type="text" placeholder="Search" class="recipe-search-box">

app/views/home/_swap_vitals.html.erb
<div class="dashboard-table swap-vitals">
  <div class="dashboard-table-row">
    <div class="dashboard-table-cell header">Swap Location</div>
    <div class="dashboard-table-cell header">Day</div>
    <div class="dashboard-table-cell header">Time</div>
  </div>
  <div class="dashboard-table-row">
    <div class="dashboard-table-cell"><%= week.swap_location %></div>
    <div class="dashboard-table-cell"><%= week.swap_date.strftime("%A %m/%d") %></div>
    <div class="dashboard-table-cell"><%= week.swap_time %></div>
  </div>
</div>

app/views/home/_swapboard_partial.html.erb
<div class="row">
  <div class="u-full-width">
    <div class="row">
      <div class="six columns">
        <h4><%= @group.name %> Swapboard</h4>
      </div>

      <div class="six columns">
        <% if @group.weeks.empty? && @is_admin %>
          <p>Now you need to create your swapping schedule.</p>
          <%= link_to new_group_week_path(@group.name)  do %>
            <p><%= fa_icon "plus" %> Get started</p>
          <% end %>
        <% elsif @group.weeks.empty? && !@is_admin %>
          <p>The schedule hasn't been created yet. Check back soon</p>
        <% end %>

        <% if @group.members.count == 1 && @is_admin %>
          <p>You need to invite some more swappers!</p>
          <%= link_to group_members_path(@group.name) do %>
            <p><%= fa_icon "users" %> Add swappers</p>
          <% end %>
        <% end %>
      </div>
    </div>

    <% unless @group.weeks.empty? %>
      <div class="row">
        <div class="six columns">
          <% if @group.current_week %>
            <%= render partial: "home/swapboard_week_list", locals: { week: @group.current_week, header: "Current Week" } %>
          <% else %>
            <%= render partial: "home/empty_week" %>
          <% end %>
          <% if @group.next_week %>
            <%= render partial: "home/swapboard_week_list", locals: { week: @group.next_week, header: "Next Week" } %>
          <% else %>
            <%= render partial: "home/empty_week" %>
          <% end %>
        </div>

        <div class="six columns">
          <% if @group.last_week %>
            <%= render partial: "home/swapboard_week_list", locals: { week: @group.last_week, header: "Last Week" } %>
          <% else %>
            <%= render partial: "home/empty_week" %>
          <% end %>

          <% if @group.leaderboard %>
            <%= render partial: "home/leaderboard" %>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="row messages-section">
      <div class="u-full-width">
        <%= render partial: "messages/messageboard", locals: { new_message: @new_message, group: @group } %>
      </div>
    </div>
  </div>
</div>

app/views/home/_swapboard_week_list.html.erb
<% unless local_assigns[:header].nil? %>
  <h6><%= header %> - Week of <%= week.start_date.strftime("%m/%d") %> </h6>
<% end %>

<div class="dashboard-table this-week">
    <div class="dashboard-table-row">
      <div class="dashboard-table-cell header">Swapper</div>
      <div class="dashboard-table-cell header">Dish</div>
      <div class="dashboard-table-cell header">Category</div>
    </div>
  <% if week.paused %>

  <div class="dashboard-table-row empty-week">
    <div class="dashboard-table-cell empty-week">
      <span class="paused"><%= fa_icon "exclamation-circle" %> Swap paused</span>
      </div>
    <div class="dashboard-table-cell empty-week"></div>
    <div class="dashboard-table-cell empty-week"></div>
  </div>

  <% else %>
    <% @group.active_users.each do |member| %>
      <div class="dashboard-table-row">
        <div class="dashboard-table-cell above-rating-row">
          <%= link_to group_member_path(@group.name, member) do %>
              <%= member.name %>
          <% end %>
        </div>
        <div class="dashboard-table-cell above-rating-row">
          <% @week_meal = member.week_meal(week) %>
          <% if @week_meal && @week_meal.name.presence %>
            <%= image_tag @week_meal.picture.url(:thumb), width: '25', class: 'img-circle profile-img' %>
            <%= link_to group_week_meal_path(@group.name, week, @week_meal) do %>
              <%= @week_meal.name %>
            <% end %>
          <% elsif member == current_user %>
              <%= link_to "Add my meal", new_group_week_meal_path(@group.name, week) %>
          <% else %>
            ???
          <% end %>
        </div>
        <div class="dashboard-table-cell above-rating-row">
          <% if @week_meal && @week_meal.category.presence %>
            <%= @week_meal.category.name %> 
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/home/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="u-full-width">
      <% unless @groups.empty? %>
        <p class="medium"><%= fa_icon "users" %> My groups</p>
        <%= render "groups/group_card", collection: @groups %>
      <% else %>
        <p>You aren't in any groups yet.</p>
      <% end %>
    </div>
  </div>
  <div class="u-full-width">
    <%= link_to new_group_path  do %>
      <p><%= fa_icon "plus" %> Nobody swaps alone. Start a group here.</p>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div class="row center-content homepage-frame">
  <div class="u-full-width">
  
    <%= render partial: "shared/alerts" %> 

    <%= image_tag "icon-only-black-small.jpg", width: "300" %>
    <p class="crockswap">Crockswap</p>
    <p class="medium tag-line">Cook once. Eat all week.</p>
    <%= link_to "Sign up", new_user_registration_path, {class: "button homepage-sign-up"} %>
    <p class='sign-in'>or</p>
    <p class='sign-in'><%= link_to "Sign in", new_user_session_path, {class: "button homepage-sign-up"} %></p>
  </div>
</div>

<div class="row center-content about-frame">
  <div>
    <p class="medium homepage-copy-block">Crockswap was created for working families who want healthy, home-cooked meals without the hassle.</p>
    <p>Steps to a Swap</p>

    <div class="container">
      <div class="row">
        <div class="four columns about-steps">
          <%= fa_icon "users 3x" %>
          <p>Start a group</p>
          <p class="step-content">Find 2 - 3 families who also stress about meal-planning, shopping, and cooking.</p>
        </div>
        <div class="four columns about-steps">
          <%= fa_icon "shopping-basket 3x" %>
          <p>Plan</p>
          <p class="step-content">Set up your group in Crockswap, enter your meal for the week.</p>
        </div>
        <div class="four columns about-steps">
          <%= fa_icon "flask 3x" %>
          <p>Cook</p>
          <p class="step-content">Make enough servings to feed each family, divide into containers.</p>
        </div>
      </div>

      <div class="row">
        <div class="four columns about-steps">
          <%= fa_icon "hand-peace-o 3x" %>
          <p>Swap</p>
          <p class="step-content">Meet, swap meals.</p>
        </div>
        <div class="four columns about-steps">
          <%= fa_icon "cutlery 3x" %>
          <p>Eat</p>
          <p class="step-content">Enjoy home-cooked, hassle-free meals all week.</p>
        </div>
        <div class="four columns about-steps">
          <%= fa_icon "repeat 3x" %>
          <p>Repeat!</p>
          <p class="step-content">Rate and comment on each other's meals in Crockswap.</p>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/home/swapboard.html.erb
<div class="container">
  <% unless @groups.empty? %>
    <%= render partial: "shared/toolbar", locals: { group: @group } %>
  <% end %>
  <div class="row">
    <div class="u-full-width">
      <% unless @groups.empty? %>
        <%= render "home/swapboard_partial", object: @group %>
      <% else %>
        <p>You aren't in any groups yet.</p>
        <%= link_to new_group_path do %>
          <p><%= fa_icon "users" %> Start a group</p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/temp_index.html.erb
<div class="row center-content homepage-frame">
  <div class="u-full-width">
    <%= image_tag "icon-only-black-small.jpg", width: "300" %>
    <p class="crockswap">Crockswap</p>
    <p class="medium tag-line">Spend less. Cook once. Eat all week.</p>
    <p class="medium">Nobody swaps alone.</p>

    <h1>COMING SOON!</h1>

  </div>
</div>

<div class="row center-content about-frame">
  <div>
    <p class="medium homepage-copy-block">Crockswap facilitates meal sharing for working families who can't find the time to shop frugally, cook efficiently, and eat healthily.</p>
    <p>Steps to a Swap</p>

    <div class="container">
      <div class="row">
        <div class="four columns about-steps">
          <%= fa_icon "users 3x" %>
          <p>Start a group</p>
        </div>
        <div class="four columns about-steps">
          <%= fa_icon "shopping-basket 3x" %>
          <p>Shop</p>
        </div>
        <div class="four columns about-steps">
          <%= fa_icon "flask 3x" %>
          <p>Cook</p>
        </div>
      </div>

      <div class="row">
        <div class="six columns about-steps">
          <%= fa_icon "hand-peace-o 3x" %>
          <p>Swap</p>
        </div>
        <div class="six columns about-steps">
          <%= fa_icon "cutlery 3x" %>
          <p>Eat</p>
        </div>
      </div>
    </div>

  </div>
</div>